// College-wise department mapping for Silver Oak University

export const COLLEGE_DEPARTMENTS: Record<string, string[]> = {
  'Silver Oak College Of Engineering & Technology': [
    'C.E (Computer Engineering)',
    'C.S.E (Computer Science & Engineering)',
    'C.S.E AIML (Artificial Intelligence & Machine Learning)',
    'C.S.E CS (Cyber Security)',
    'IT (Information Technology)',
    'BioTech',
    'Civil Engineering',
    'Mechanical Engineering',
    'Aeronautical Engineering',
  ],
  'Aditya Silver Oak Institute of Technology': [
    'C.E (Computer Engineering)',
    'C.S.E (Computer Science & Engineering)',
    'C.S.E AIML (Artificial Intelligence & Machine Learning)',
    'C.S.E CS (Cyber Security)',
    'IT (Information Technology)',
    'BioTech',
    'Civil Engineering',
    'Mechanical Engineering',
    'Aeronautical Engineering',
    'Diploma C.E (Computer Engineering)',
    'Diploma C.S.E (Computer Science & Engineering)',
    'Diploma C.S.E AIML (Artificial Intelligence & Machine Learning)',
    'Diploma C.S.E CS (Cyber Security)',
    'Diploma IT (Information Technology)',
    'Diploma BioTech',
    'Diploma Civil Engineering',
    'Diploma Mechanical Engineering',
    'Diploma Aeronautical Engineering',
  ],
  'Silver Oak College of Humanities & Social Sciences': [
    'BA English',
    'BA Psychology',
    'BA Sociology',
    'BA Economics',
    'BA Political Science',
    'MA English',
    'MA Psychology',
    'MA Sociology',
  ],
  'Silver Oak College of Computer Applications': [
    'BCA',
    'MCA',
    'IMSCIT',
    'BSC IT',
    'BSC CS IT',
    'MSC IT',
    'MSC CS IT',
  ],
  'Silver Oak Institute of Science': [
    'BSc Physics',
    'BSc Chemistry',
    'BSc Mathematics',
    'BSc Biotechnology',
    'BSc Microbiology',
    'MSc Physics',
    'MSc Chemistry',
    'MSc Mathematics',
  ],
  'Silver Oak Institute of Management': [
    'BBA',
    'MBA',
    'MBA HR',
    'MBA Finance',
    'MBA Marketing',
    'MBA International Business',
  ],
  'Silver Oak Commerce College': [
    'B.Com',
    'B.Com Honours',
    'M.Com',
    'B.Com (Banking & Insurance)',
    'B.Com (Taxation)',
  ],
  'Silver Oak College of Vocational Education': [
    'Vocational IT',
    'Vocational Retail Management',
    'Vocational Fashion Design',
    'Vocational Interior Design',
    'Vocational Hospitality',
  ],
  'Silver Oak Law College': [
    'BA LLB',
    'BBA LLB',
    'LLB',
    'LLM',
  ],
  'Silver Oak College of Physiotherapy': [
    'BPT (Bachelor of Physiotherapy)',
    'MPT (Master of Physiotherapy)',
    'MPT Ortho',
    'MPT Neuro',
    'MPT Sports',
  ],
  'Silver Oak Pharmacy College': [
    'B.Pharm',
    'M.Pharm',
    'D.Pharm',
    'Pharm.D',
  ],
  'Silver Oak College of Nursing': [
    'B.Sc Nursing',
    'M.Sc Nursing',
    'GNM',
    'ANM',
  ],
  'Silver Oak Institute of Business Management': [
    'BBA',
    'MBA',
    'BMS',
    'Executive MBA',
    'PGDM',
  ],
  'Silver Oak College of Liberal Studies': [
    'BA Liberal Arts',
    'BSc Liberal Studies',
    'MA Liberal Studies',
  ],
  'Silver Oak College of Animation & Multimedia': [
    'BSc Animation',
    'BSc Multimedia',
    'BSc Game Design',
    'BSc VFX',
    'Diploma in Animation',
    'Diploma in Multimedia',
  ],
  'Silver Oak College of Aviation & Technology': [
    'BSc Aviation',
    'BBA Aviation Management',
    'Diploma in Aviation',
    'Aircraft Maintenance Engineering',
  ],
  'Silver Oak Institute of Design': [
    'B.Des Fashion Design',
    'B.Des Interior Design',
    'B.Des Product Design',
    'B.Des Graphic Design',
    'M.Des',
  ],
};

export const COURSE_DURATIONS = [
  '2 Years',
  '3 Years',
  '4 Years',
  '5 Years',
  '6 Years',
];

export function getDepartmentsForCollege(collegeName: string): string[] {
  return COLLEGE_DEPARTMENTS[collegeName] || [];
}
