import { useState, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';

export interface CollectionDrive {
  id: string;
  name: string;
  description: string | null;
  drive_date: string | null;
  status: string;
  created_by: string | null;
  created_at: string;
}

export interface CollectionReceipt {
  id: string;
  receipt_number: string;
  drive_id: string | null;
  donor_type: 'internal' | 'external';
  member_id: string | null;
  donor_name: string | null;
  donor_college: string | null;
  donor_whatsapp: string | null;
  item_type: string;
  quantity: number;
  unit: string | null;
  notes: string | null;
  collection_date: string;
  collected_by: string | null;
  created_at: string;
  // Joined data
  member?: {
    uid: string;
    first_name: string;
    last_name: string;
    whatsapp_number: string | null;
    academic_department: string | null;
    college_name: string | null;
  } | null;
  drive?: {
    name: string;
  } | null;
}

export interface CreateReceiptData {
  drive_id?: string;
  donor_type: 'internal' | 'external';
  member_id?: string;
  donor_name?: string;
  donor_college?: string;
  donor_whatsapp?: string;
  item_type: string;
  quantity: number;
  unit?: string;
  notes?: string;
  collection_date?: string;
}

export function useCollectionDrives() {
  const [drives, setDrives] = useState<CollectionDrive[]>([]);
  const [receipts, setReceipts] = useState<CollectionReceipt[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const { toast } = useToast();

  const fetchDrives = async () => {
    const { data, error } = await supabase
      .from('collection_drives')
      .select('*')
      .order('created_at', { ascending: false });

    if (error) {
      toast({
        title: 'Error fetching drives',
        description: error.message,
        variant: 'destructive',
      });
      return;
    }

    setDrives(data || []);
  };

  const fetchReceipts = async () => {
    const { data, error } = await supabase
      .from('collection_receipts')
      .select(`
        *,
        drive:collection_drives(name)
      `)
      .order('created_at', { ascending: false });

    if (error) {
      toast({
        title: 'Error fetching receipts',
        description: error.message,
        variant: 'destructive',
      });
      return;
    }

    // Fetch member details for internal donors
    if (data) {
      const memberIds = data
        .filter(r => r.donor_type === 'internal' && r.member_id)
        .map(r => r.member_id);

      if (memberIds.length > 0) {
        const { data: members } = await supabase
          .from('profiles')
          .select('user_id, uid, first_name, last_name, whatsapp_number, academic_department, college_name')
          .in('user_id', memberIds);

        const receiptsWithMembers = data.map(receipt => ({
          ...receipt,
          member: members?.find(m => m.user_id === receipt.member_id) || null,
        }));

        setReceipts(receiptsWithMembers as CollectionReceipt[]);
        return;
      }
    }

    setReceipts((data || []) as CollectionReceipt[]);
  };

  const fetchData = async () => {
    setIsLoading(true);
    await Promise.all([fetchDrives(), fetchReceipts()]);
    setIsLoading(false);
  };

  const createDrive = async (data: { name: string; description?: string; drive_date?: string }) => {
    const { error } = await supabase
      .from('collection_drives')
      .insert(data);

    if (error) {
      toast({
        title: 'Error creating drive',
        description: error.message,
        variant: 'destructive',
      });
      return { success: false };
    }

    toast({ title: 'Drive created successfully' });
    await fetchDrives();
    return { success: true };
  };

  const createReceipt = async (data: CreateReceiptData) => {
    // receipt_number is auto-generated by trigger
    const { data: newReceipt, error } = await supabase
      .from('collection_receipts')
      .insert([{
        receipt_number: '', // Will be replaced by trigger
        drive_id: data.drive_id,
        donor_type: data.donor_type,
        member_id: data.member_id,
        donor_name: data.donor_name,
        donor_college: data.donor_college,
        donor_whatsapp: data.donor_whatsapp,
        item_type: data.item_type,
        quantity: data.quantity,
        unit: data.unit || 'pieces',
        notes: data.notes,
        collection_date: data.collection_date || new Date().toISOString().split('T')[0],
      }])
      .select()
      .single();

    if (error) {
      toast({
        title: 'Error creating receipt',
        description: error.message,
        variant: 'destructive',
      });
      return { success: false };
    }

    toast({ title: 'Receipt created successfully' });
    await fetchReceipts();
    return { success: true, receipt: newReceipt };
  };

  const deleteReceipt = async (id: string) => {
    const { error } = await supabase
      .from('collection_receipts')
      .delete()
      .eq('id', id);

    if (error) {
      toast({
        title: 'Error deleting receipt',
        description: error.message,
        variant: 'destructive',
      });
      return { success: false };
    }

    toast({ title: 'Receipt deleted successfully' });
    await fetchReceipts();
    return { success: true };
  };

  useEffect(() => {
    fetchData();
  }, []);

  return {
    drives,
    receipts,
    isLoading,
    createDrive,
    createReceipt,
    deleteReceipt,
    fetchData,
  };
}
